### ISSUE TITLE
Cursor theme not being shown in lxappearence

### ISSUE THREAD

**Issue by legendofmiracles** [im-AMS/LiOSV-cursors#1]
So the cursor theme is not being shown in lxappearence.. 
when i press the button to add a new cursor theme, it only lets me choose between tar.gz and tar.bz2

What can i do to allow me to change the theme?

**Comment by im-AMS** [comment]
actually this is just a repo for the raw files... u r free to compile... but it would be a waste of time... just download the cursor from
pling or KDE store, it's a compiled version...

after u download u just need to extract it to
`~/. local/share/icons` for single user install
and `/usr/share/icons` for all users (remember u need root privileges for this)

hope I answered wat u wer looking for!

**Comment by legendofmiracles** [comment]
I downloaded it from pling and then dragged it in .local/usr/share/icons. I suppose my question should be how to enable the cursor theme..

**Comment by im-AMS** [comment]
well the arch wiki has to say this

`LXAppearance

LXAppearance sets the default cursor by creating an ~/.icons/default/index.theme file: if you edited that file manually, LXAppearance will overwrite it. Remember to also edit ~/.config/gtk-3.0/settings.ini manually as specified in #XDG specification, because applications like Firefox use this setting instead. `

why don't u drop it here?
