### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by silvi** [im-AMS/LiOSV-cursors#2]
This cursor theme looks wonderful! I was already using Posy's and was missing the MacOS inspired hands.

Will there be a Windows release?

Thanks.

**Comment by im-AMS** [comment]
thanks!

actually the script which generates it was borrowed(link in Readme) since he has mentioned it will soon be made... I have no choice but to wait... I have trued making it manually.... but ohh boi it's a pain, not to mention it dint work well😅. I'm personally waiting to use my own cursors on windows 😂
